name: BYOR phase 2
on:
  schedule:
    - cron: '1 00 * * *'
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Delete existing project from the repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - name: Build a Ballerina simple service project
        uses: ballerina-platform/ballerina-action@master
        with:
          args: 
            new -t service test

      - name: Add new Ballerina project with latest version
        run: |
          cd /home/runner/work/test-19-sep/test-19-sep/test
          rm -f bal.deb
          git add *
          git commit -m "Add new Ballerina project"
          git push
