name: BYOR phase 2
on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: choreoanonymouspullable.azurecr.io/choreoipaas/choreo-ballerina-devcontainer:2201.1.2
      options: --user root
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Delete existing repository
        run: |
          git config --global --add safe.directory /__w/byor-greetings-app2/byor-greetings-app2
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout feature1
          if [ -d hello_service ]; then
            git rm -r hello_service
            git commit -m "Deleted existing folder from the repository"
            git push origin feature1
          fi
          
      - name: Build a Ballerina simple service project
        run: |
          bal new -t service hello_service

      - name: Add new Ballerina project with latest version
        run: |
          cd /__w/byor-greetings-app2/byor-greetings-app2
          rm -f bal.deb
          git add *
          git commit -m "Add new Ballerina project"
          git push origin feature1
